version: '2'
services:
    musicservice-app:
        image: musicservice
        external_links:
            - musicservice-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=MusicService
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    musicservice-mongodb:
        extends:
            file: mongodb.yml
            service: musicservice-mongodb
