version: '2'
services:
    musicservice-mongodb:
        container_name: musicservice-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/MusicService/mongodb/:/data/db/
